# Generated by Django 4.2.2 on 2023-07-01 13:18

import django.core.validators
from django.db import migrations, models

import core.enums
import links.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(max_length=core.enums.Limits['MAX_LEN_ORIGINAL_LINK'], unique=True, verbose_name='Оригинальная ссылка')),
                ('short_url', models.CharField(blank=True, db_index=True, max_length=core.enums.Limits['MAX_LEN_LINK_SHORT_CODE'], unique=True, validators=[links.validators.ShortURLValidator, django.core.validators.MinValueValidator(limit_value=core.enums.Limits['MAX_LEN_LINK_SHORT_CODE'])], verbose_name='Короткий код ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Короткая ссылка',
                'verbose_name_plural': 'Короткие ссылки',
            },
        ),
        migrations.AddConstraint(
            model_name='shortlink',
            constraint=models.UniqueConstraint(fields=('original_link', 'short_url'), name='unique_link_shortcode'),
        ),
    ]
