# Generated by Django 4.2.2 on 2024-01-31 14:47

from django.db import migrations, models

import links.validators


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='color',
            field=models.CharField(default='', max_length=7, validators=[links.validators.HexColorValidator], verbose_name='Цвет'),
        ),
    ]
