# Generated by Django 4.2.2 on 2024-02-27 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shortlink",
            options={
                "verbose_name": "Короткая ссылка",
                "verbose_name_plural": "Короткие ссылки",
            },
        ),
    ]
