# Generated by Django 4.2.2 on 2023-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Переходов по ссылке'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна ли ссылка?'),
        ),
    ]
