# Generated by Django 4.2.2 on 2023-06-30 19:07

from django.db import migrations, models

import links.validators


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlink',
            name='short_url',
            field=models.CharField(db_index=True, max_length=6, unique=True, validators=[links.validators.ShortURLValidator()], verbose_name='Короткий код ссылки'),
        ),
    ]
