# Generated by Django 4.2.2 on 2023-07-10 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercampaign',
            name='unique_name_per_owner',
        ),
        migrations.AlterField(
            model_name='aliasshortlink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alias_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец пользовательской ссылки'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец короткой ссылки'),
        ),
        migrations.AddConstraint(
            model_name='usercampaign',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_campaign_name_per_owner', violation_error_message='Такая компания уже существует.'),
        ),
    ]
