# Generated by Django 4.2.2 on 2024-01-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_usergroup_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя группы'),
        ),
    ]
