# Generated by Django 4.2.2 on 2023-07-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_shortlink_clicks_count_shortlink_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее время клика'),
        ),
    ]
