# Generated by Django 4.2.2 on 2024-08-16 09:16

import django.db.models.deletion
from django.db import models, migrations

import core.enums
import links.validators


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_alter_shortlink_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=core.enums.Limits["MAX_LEN_COLOR_NAME"],
                        verbose_name="Имя цвета",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[links.validators.HexColorValidator],
                        verbose_name="HEX Цвета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
                "db_table": "links_color",
            },
        ),
        migrations.AlterField(
            model_name="usergroup",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_color",
                to="links.color",
                verbose_name="Цвет группы",
            ),
        ),
    ]
