# Generated by Django 4.2.2 on 2023-07-05 20:47

import django.core.validators
from django.db import migrations, models

import links.validators


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_shortlink_last_clicked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliasShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_link', models.URLField(max_length=2000, unique=True, verbose_name='Оригинальная ссылка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('clicks_count', models.PositiveIntegerField(default=0, verbose_name='Переходов по ссылке')),
                ('last_clicked_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее время клика')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна ли ссылка?')),
                ('alias', models.CharField(blank=True, db_index=True, max_length=30, unique=True, validators=[links.validators.AliasShortURLValidator, django.core.validators.MinValueValidator(limit_value=5)], verbose_name='Пользовательское имя ссылки')),
            ],
            options={
                'verbose_name': 'Пользовательская короткая ссылка',
                'verbose_name_plural': 'Пользовательские короткие ссылки',
                'ordering': ['original_link', 'alias', 'created_at', 'clicks_count', 'last_clicked_at', 'is_active'],
            },
        ),
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ['original_link', 'short_url', 'created_at', 'clicks_count', 'last_clicked_at', 'is_active'], 'verbose_name': 'Короткая ссылка', 'verbose_name_plural': 'Короткие ссылки'},
        ),
        migrations.AddConstraint(
            model_name='aliasshortlink',
            constraint=models.UniqueConstraint(fields=('original_link', 'alias'), name='unique_alias_link'),
        ),
    ]
