# Generated by Django 4.2.2 on 2024-08-27 14:37

import core.enums
import django.core.validators
from django.db import migrations, models
import links.validators


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_alter_color_color_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_hex',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=4), django.core.validators.MaxLengthValidator(limit_value=7), links.validators.HexColorValidator()], verbose_name='HEX Цвета'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='short',
            field=models.CharField(db_index=True, max_length=core.enums.Limits['MAX_LEN_LINK_SHORT_CODE'], unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=core.enums.Limits['MIN_LEN_LINK_SHORT_CODE']), django.core.validators.MaxLengthValidator(limit_value=core.enums.Limits['MAX_LEN_LINK_SHORT_CODE'])], verbose_name='Короткий код ссылки'),
        ),
    ]
