# Generated by Django 4.2.2 on 2023-07-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_aliasshortlink_alter_shortlink_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aliasshortlink',
            options={'ordering': ['original_link', 'alias', 'created_at', 'clicks_count', 'last_clicked_at', 'is_active'], 'verbose_name': 'Пользовательская ссылка', 'verbose_name_plural': 'Пользовательские ссылки'},
        ),
    ]
