# Generated by Django 4.2.2 on 2023-07-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_alter_aliasshortlink_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aliasshortlink',
            table='links_alias_link',
        ),
    ]
