# Generated by Django 4.2.2 on 2024-02-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_usergroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouplink',
            name='alias_link',
            field=models.ForeignKey(blank=True, db_column='alias_link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='links.aliasshortlink', verbose_name='Пользовательская ссылка группы'),
        ),
        migrations.AlterField(
            model_name='usergrouplink',
            name='group',
            field=models.ForeignKey(db_column='group', on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='links.usergroup', verbose_name='Группа пользователя'),
        ),
        migrations.AlterField(
            model_name='usergrouplink',
            name='short_link',
            field=models.ForeignKey(blank=True, db_column='short_link', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='links.shortlink', verbose_name='Короткая ссылка группы'),
        ),
    ]
