# Generated by Django 4.2.2 on 2024-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_usergrouplink_alias_link_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usergrouplink',
            name='unique_alias_link_per_group',
        ),
        migrations.RemoveConstraint(
            model_name='usergrouplink',
            name='unique_short_link_per_group',
        ),
        migrations.AddConstraint(
            model_name='usergrouplink',
            constraint=models.UniqueConstraint(condition=models.Q(('alias_link__isnull', False)), fields=('group', 'alias_link'), name='unique_alias_link_per_group'),
        ),
        migrations.AddConstraint(
            model_name='usergrouplink',
            constraint=models.UniqueConstraint(condition=models.Q(('short_link__isnull', False)), fields=('group', 'short_link'), name='unique_short_link_per_group'),
        ),
    ]
